# Generated by Django 2.2.8 on 2020-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='idx_author_name'),
        ),
    ]
