# Generated by Django 2.2.8 on 2020-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200425_1757'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_name',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='idx_book_title'),
        ),
    ]
